# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a6c1a9acfc6859f61ffc9dbe192dc515"
name = "financenonplus"
handle = "financenonplus"
application_url = "https://expand-examples-luggage-mode.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "financenonplus.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://expand-examples-luggage-mode.trycloudflare.com/auth/callback",
  "https://expand-examples-luggage-mode.trycloudflare.com/auth/shopify/callback",
  "https://expand-examples-luggage-mode.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
