# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a6c1a9acfc6859f61ffc9dbe192dc515"
name = "Consors Finanzierung Commerce-Pro"
handle = "financenonplus"
application_url = "https://financenonplus.cpro-server.de"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "financenonplus.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://financenonplus.cpro-server.de/auth/callback",
  "https://financenonplus.cpro-server.de/auth/shopify/callback",
  "https://financenonplus.cpro-server.de/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
